### ISSUE TITLE
running `pytui` does not work.

### ISSUE THREAD

**Issue by 9y2070m** [martinsmid/pytest-ui#11]
I wanted to test your interface, therefore I installed it using pip `pip install pytest-ui`

When I run `pytui` I get following console output.

```
Traceback (most recent call last):
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\Scripts\pytui.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\pytui\ui.py", line 748, in main
    ui.run()
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\pytui\ui.py", line 523, in run
    self.main_loop = urwid.MainLoop(
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\urwid\main_loop.py", line 115, in __init__
    screen = raw_display.Screen()
  File "C:\Users\ThoGan00\AppData\Local\Programs\Python\Python38\lib\site-packages\urwid\raw_display.py", line 92, in __init__
    fcntl.fcntl(self._resize_pipe_rd, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

```

**Comment by martinsmid** [comment]
Hi, thank you for your report. I didn't test it on windows and it seems that the urwid library that `pytest-ui` uses doesn't work with windows. 

However, it is common to use `cygwin` or `WSL` to get a linux-like terminal on windows. You could give that a try.
